name: Database Migration Check

on:
  pull_request:
    paths:
      - 'prisma/**'
      - 'package.json'
      - 'package-lock.json'

jobs:
  check-migrations:
    name: Check Database Migrations
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Check for pending migrations
        run: |
          # Create a temporary database
          export DATABASE_URL="file:./migration-check.db"
          npx prisma db push --force-reset
          npx prisma migrate status
          
      - name: Validate schema
        run: npx prisma validate

      - name: Check if seed script runs
        run: |
          export DATABASE_URL="file:./seed-check.db"
          npx prisma db push --force-reset
          npm run db:seed
        env:
          DATABASE_URL: file:./seed-check.db
